### ISSUE TITLE
Leaving activity on different device does not automatically update My Activities screen

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#102]
If you have joined an activity, then leave it from another device, the activity will remain in "joined" until you re-query (likely also if you re-appear the tab)

Maybe not something that's crucial since most users won't be joining/leaving from two devices at a time, but documenting here anyway.

**Comment by noahtallen** [comment]
is the my activities screen using `useActivity` and updating when activities update? Slash are other activity table screens doing that? At the least, view activity should work properly even in this case.

**Comment by noahtallen** [comment]
We could consider this bug fixed now that we have swipe to refresh. Thoughts?

**Comment by JakeThurman** [comment]
Good enough for me!
