### ISSUE TITLE
Half-created accounts creates dead-end login screen

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#105]
If you sign up, but don't fill out the bio/profile picture screen, your `accounts` document is never created and so you can never sign into that account or re-create an account with that email.

1. Sign up with an email address, without filling out bio/profile picture
2. Close the app
3. Open the app on a different device (or same device, cleared cache, reinstalled, etc)
4. Try to login

Nothing will happen, and no warnings will appear.  You cannot create an account with your email and you cannot log in with the email.

Kind of tricky to do this unless you try to sign up partially one one device and partially on another, so probably not a big deal.

**Comment by noahtallen** [comment]
good catch! I had expected it would work like:
- delete the app without filling out bio
- reinstall or something, then actually login with that email/password, and be taken to the bio screen

that's not what should happen though, it should probably defer creating the account or something... which I think is possible.

**Comment by JakeThurman** [comment]
This is fixed. You can log in, and are able to finish setting up your account there.

**Comment by JakeThurman** [comment]
(I tested)
