### ISSUE TITLE
Josh is the only user

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#111]
![IMG_0429](https://user-images.githubusercontent.com/6265975/55088697-8b076900-5082-11e9-899f-1ae55c3e92d0.PNG)

**Comment by noahtallen** [comment]
Also, note that navigating to any activity with users other than josh results in a blank screen.

**Comment by JakeThurman** [comment]
Please note, this is not Josh specifically. This is whoever is the logged in user.
