### ISSUE TITLE
you still get notifications even after logging out

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#123]
We need to null the notification token when logging out

**Comment by JakeThurman** [comment]
lol

**Comment by noahtallen** [comment]
this is actually harder to solve than it sounds lol. We could disable notifications when you hit log out. But when you open it, it'll immediately re-register, because the registration happens in app delegage. We could null the notification token on log out, but then it'll get re-set when you open the app again. So we'd have to totally refactor how we get notification access in the first place. We'd have to move notification registration to somewhere at the end of the login flow, which seems hard, especially because we still want firebase to "listen" for updates to the notification token, which should probably stay in app delegate so it doesn't go out of scope

**Comment by noahtallen** [comment]
Unless we guard having a uid when getting the notification token. - ie we guard on having to be logged in before updating the token Genius. I'll do that.

**Comment by JakeThurman** [comment]
I was thinking that and you responded to yourself before I could lol. If we're logged out it won't have anywhere to write the notification token anyway.
