### ISSUE TITLE
Topics are duplicated on real iPhone XR

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#13]
Scrolling through the topics list, one can see duplicate topic if you go down far enough.

**Comment by noahtallen** [comment]
Pinging @lukemeierj this issue is happening again. I'm about to patch the issue in View Activity and on the Profile by removing duplicates there, but we should also fix the root issue

**Comment by lukemeierj** [comment]
Are you sure you aren't referring to #92 ?

**Comment by lukemeierj** [comment]
Yikes, so this is happening because the closure in `collection.getDocuments` is called twice in `FirestoreManager` and there's no cleanup between calls.
