### ISSUE TITLE
Chat box blocks the "^" button

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#136]
It's been a bug, but it got through CR so I'm putting it here for our metrics.

**Comment by lukemeierj** [comment]
We might be able to close this, since even though it fails in UI tests, Grant fixed it for normal use cases.

**Comment by noahtallen** [comment]
Closed in #129. I think luke's right about the UI test thing. It's a weird edge case, but all seems to be fixed using it IRL.
