### ISSUE TITLE
Removed self from my own created activity

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#142]
I created an activity.  Person X joined.  I reported person X.  I was banned and removed from my own activity.  

That's not really what we want.  Better to remove the reported user in this one case.

**Comment by noahtallen** [comment]
Yeah that's crazy! So instead, we want to ban and remove the reported user?

**Comment by noahtallen** [comment]
This is probably also an issue with shared activities: If you own activities that you share with a user, if you report that user, you'll even be removed from other activities that you own if that user is also in them.
