### ISSUE TITLE
Load main app view despite not being logged in

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#18]
I opened my iPad's build and accessed the main tab bar interface.  No topics loaded (presumably because we lacked permissions).  I closed then reopened, and was directed to the login screen.

**Comment by noahtallen** [comment]
Could you clarify on what happened when before you opened the iPad's build? Did you manually log out at some point?

I guess this means that we need to be better at listening to auth change, because it should notify us when we don't have auth any more

**Comment by lukemeierj** [comment]
If I recall correctly, I opened the app on my iPad (not connected to the computer).  I'm not sure if it was already opened.  

I saw no topics.

I closed the app, and reopened it.  It prompted me to sign on, implying that I had no credentials prior

**Comment by lukemeierj** [comment]
This is (probably) where we don't wait for auth to succeed before passing through to the main screen.
cc @JakeThurman

**Comment by JakeThurman** [comment]
right. the problem is that we just transition, no wiat

**Comment by noahtallen** [comment]
We could stick in a full screen loading indicator or keep showing the launch screen until auth loads
