### ISSUE TITLE
On the view activity cell, user pictures are wacky

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#56]
Some things that happen:
- Activity cell has two different pictures
- Tap on activity and view it - there is only one user!
- Go back to the table view and look at the cell again. it now has two pictures, but they're both the same.

There should be only one. I haven't been able to reliably reproduce this, but it happens very frequently. I think you could reproduce it by tapping into and out of a lot of activities.

**Comment by noahtallen** [comment]
This is still an issue - noticed today before merging jake's PR #70. It was ( I think ) up to date with master at the time

**Comment by lukemeierj** [comment]
There is only one user in this activity.

<img width="350" alt="screen shot 2019-02-28 at 2 43 32 pm" src="https://user-images.githubusercontent.com/7787605/53593674-4661de00-3b67-11e9-98eb-4e5e4e039b07.png">
