### ISSUE TITLE
Time is always "This Month"

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#61]
Every activity seems to have "This month" listed as its string.

**Comment by lukemeierj** [comment]
This is an issue with the `CreateActivityVC`.

The start and end date are set as:
```
start_time: getSliderDate(sliderValue: dateSlider.minValue),
end_time: getSliderDate(sliderValue: dateSlider.maxValue)
```
But even for today through 3 days from now, the duration of the range is a month.

@gyurisic Could you take a look at this?

**Comment by noahtallen** [comment]
Oh interesting. I did notice that as well

**Comment by noahtallen** [comment]
@gyurisic Maybe `dateSlider.minValue` refers to the minimum possible value rather than the minimum selected value?

**Comment by JakeThurman** [comment]
lol it does

**Comment by JakeThurman** [comment]
I'll take this issue

**Comment by noahtallen** [comment]
@JakeThurman Grant has already done this in his open PR #72
