### ISSUE TITLE
The Activity list does not appear to update when navigating away and back to the screen

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#71]
For example, when the member list of an activity changes, the pictures on the list do not update.

To duplicate, (on the latest branch which includes leaving an activity), go to an activity you're a member of which has 3 or less members. Observe the (possibly) correct number of profile pictures on the activity list, then go to the activity. Leave the activity. You'll be taken back to the activity list, which will still show the activity as having the same users. Since there were 3 or so members, there should be one less picture, but it still has the original pics. See gif for this in action:

![leave_activity_bug](https://user-images.githubusercontent.com/6265975/53307329-4ca14300-3865-11e9-9c42-9be7894ca426.gif)

I think this is also an issue when you delete an activity. When you delete the activity, it takes you back to the list, but the activity will still be on the list, even though the `onInvalidate` code is called from the data manager class.

cc @lukemeierj @JakeThurman who wrote related code

**Comment by noahtallen** [comment]
I think this is related to #56

**Comment by lukemeierj** [comment]
Looks like its how `SearchFilterBar` handles its `fetchAndLoadActivities`

On line 150, we don't fetch new IDs if the query hasn't changed, and so we don't query algolia, and so we never trigger the callback that re-displays/reloads/re-inits listeners.  

```        
       //Cancel if nothing has changed
        if lastSearchParams == myParams { return }
```

Basically, we have few options that immediately come to mind:
  * Always, one way or another run `display` or `loadData` each time we `viewWillAppear`, no matter what (probably something like this is the best solution)
  * Dive into when we can and can't safely keep our listeners running.  If it's possible to `reloadAtIndex` when a table cell is hidden (which I think is impossible and caused #50 ), then we might be able to keep our listeners.

**Comment by noahtallen** [comment]
Interesting. I think we want to always run the "re-render" if activity info changes, which is definitely more frequent in our testing than normally. But it would be nice to have it "just work". I think it _would_ be good to avoid another trip to Algolia if the query hasn't changed, but I think reloading the listeners is cheap enough since everything should be in the cache already anyways. Does that line of code prevent it from calling Algolia or just prevent it from re-running the listeners?

**Comment by noahtallen** [comment]
That commit will resolve this issue. Thanks for figuring this out luke! I made sure it returned cached activity IDs in this case instead of running the algolia query. This may not be ideal, but it works for now. cc @JakeThurman could you take a look at e26f0d6 to see if it makes anything weird happen?

**Comment by lukemeierj** [comment]
Awesome, thanks for patching this @noahtallen
