### ISSUE TITLE
Daterange text in view activity cell is constrained poorly

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#73]
it cuts off after like two words of "tomorrow throuh..." (see screenshot)
<img width="394" alt="screen shot 2019-02-24 at 7 35 46 pm" src="https://user-images.githubusercontent.com/6265975/53308012-dbb15980-386b-11e9-942d-5acca8f70d6f.png">

cc @lukemeierj or @gyurisic

**Comment by lukemeierj** [comment]
For long activity titles AND long strings, what do we want?

**Comment by noahtallen** [comment]
I don't know - it seems like we need to handle the date better because I feel like we can control the max length of date strings. What if it was a dash instead of through?
  

  
  

  
  
>

**Comment by lukemeierj** [comment]
Yeah, we definitely have _more_ control.  I'll handle this one
