### ISSUE TITLE
Can't load activity that contains deleted user

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#80]
When a user is deleted, apparently the userId is not removed from the activities.

In the viewActivity screen, when any user cannot be accessed through `useUsers`, no users are returned and we cannot render an activity.

@noahtallen

**Comment by noahtallen** [comment]
We need to:
- [ ] Make the cloud function remove the user from all activities in which they participated. Note: what should we do about activities for which they are the owner? Delete them? What if the activity is "active"?
- [ ] Make sure `useUsers` doesn't complain if a single user DNE

**Comment by noahtallen** [comment]
This issue is back.
