### ISSUE TITLE
Flicker on Discover / My Activity

### ISSUE THREAD

**Issue by JadaTBK** [jack-and-the-beans/buddies-ios#87]
This is due to reloading the table view in both ViewDidLoad() and ViewWillAppear(), so yeah. We (me Jake and Grant) talked about just having time stamp and refreshing after set amount of time (like 10 minutes???)

**Comment by lukemeierj** [comment]
"me jake and grant" lol

It occurs to me now that if we don't reload and re-initialize our listers on every `viewWillAppear`, we can't clean up our listeners on every `viewWillDisappear`.  

We fixed #50 by not updating table views that are not visible.  This was a big problem then, but quickly testing removing `cleanup()` from `ActivityTableVC`'s `viewWillDisappear` shows it may be possible to safely update rows in hidden tables. 

If we find a way to safely keep our listeners for a tableview, we need to decide
* Do we want all of our listeners in all of our potential table views to be updating hidden table views indefinitely?
    * Perhaps we cleanup the listeners on a timeout
* We don't need to set a timeout for reloading the Algolia query.  We can simply check if `displayIds == self.displayIds` in `loadData(for displayIds:...) and return immediately if true (provided the listeners for users/activities are not cancelled)

**Comment by noahtallen** [comment]
i don't know what i'm doing lol. I did significantly fix this in #116, but it still breaks when the actual list of activities changes. E.g. when you navigate back to the screen, it re-queries for any new activities it might want to show. It does a diff between the existing ones and the new ones which usually doesn't have changes, but in the off chance there is a change (for instance, you left an activity from my activities), it ends up refreshing the whole list. The animation is a bit weird when it does that.

**Comment by noahtallen** [comment]
actually, I did end up almost completely fixing it now.
