### ISSUE TITLE
Favoriting a topic saves it to your collection multiple times

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#92]
Tonight while testing account propagation between users and accounts, i realized that when I favorited 3-4 activities in a row, i ended up with about 2x that number of entries in the favorite activity array on the backend. They were all duplicates. I'm not sure what causes this, but it's not every single time. So if you just favorite one activity this may not happen. Try favoriting several activities, watching your `account` document. I was testing on the `FIX-login-wait` branch. Pinging @JakeThurman and @lukemeierj

**Comment by lukemeierj** [comment]
Since this didn't happen before the `accounts`/`user` split, I'm guessing it came along with that. 

It might be that when we set `selectedTopics`, we append newly favorited topics to an array and then save that array to Firebase.  It's _possible_ that it adds duplicates since we are appending, but its a new problem so I think it's related to the replicating data.

**Comment by noahtallen** [comment]
I can verify it's not related to replicating data between accounts and users
- The error happens when setting directly to `accounts`, so it's something new to do with modifying accounts
- Replicating to `users` is a simple set operation - so all of the data is replaced with all the data from the `account`. (no kind of update or merging happening there)

**Comment by lukemeierj** [comment]
I can't replicate this from either the`topics tab` or `topics tab -> view activities`.  

You can manually add the topic to the document, but that's the only way I can get a duplicate.  It goes away when you unfavorite, and should not cause problems.

**Comment by noahtallen** [comment]
Ok. I'll check again as well
  
  

  
>

**Comment by lukemeierj** [comment]
I was able to replicate it today.

**Comment by noahtallen** [comment]
Possibly related to #13. If there are duplicated topics on the topics tab, would it save both of them to firebase?

**Comment by lukemeierj** [comment]
Resolved in #106
