### ISSUE TITLE
Bio/Profile onboarding screen flashes always

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#93]
![ezgif-5-a61891dd065e](https://user-images.githubusercontent.com/7787605/54329890-0597a980-45ea-11e9-9f00-7bbbb63f6ada.gif)

Even though I already have an account, this always happens when I open Buddies.

cc @JakeThurman Without really looking, I'm guessing is related to #90 which fixed #18

**Comment by noahtallen** [comment]
Thoughts: firebase user listener or the wrapper might return null at some point

**Comment by lukemeierj** [comment]
This also occurs when you have no account, before showing you the signup page.

**Comment by noahtallen** [comment]
I think we must use the firebase listener in the logged in flow, which
means we use that listener twice. I think we could probably make that
consistent and only use it once from app-delegate and if signed out,
_always_ start from the signup page? I'm not sure what state we have to be
in to show the bio page

**Comment by noahtallen** [comment]
I stuck breakpoints during the flow the other day, and it appears that each of them get hit:
1. Where it keeps showing the launch screen
2. Where it shows the logged out view
3. Where it shows the logged in view

So something is weird about how the listener is working in app delegate. It shouldn't fire logged out before firing logged in. Does the user logged in user return nil immediately before the query actually finishes?
