### ISSUE TITLE
Data isn't consistent throughout apps, causing lost updates

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#97]
If you have multiple devices, often one of them will have stale data and seems disconnected from Firebase.  It will not update when people join or leave activities.  

This is annoying for views not updating if your device is "disconnected", but also causes a big problem for other users.

1. Join an activity with a "connected" device on an account
2. Join the same activity with a "disconnected" device on a different account
3. The first account's membership in the activity is overwritten by the second account.

**Comment by lukemeierj** [comment]
If I change my `account.name` from the console, it will not change in the View Activity view but does live update in the Profile.

**Comment by noahtallen** [comment]
@lukemeierj @JakeThurman @gyurisic please comment with any observations you have about this issue. I've only seen it like once and am not sure where to start

**Comment by JakeThurman** [comment]
When preparing for the presentation the other day I tried to change activities in the firebase console but they didn't update anywhere in app until I closed and reopened.
